site_name: base-template Documentation
theme: 'material'
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: '#087da1'
    accent: '#00a889'
  font:
    text: 'Source Sans Pro'

repo_name: 'inetum-peru/base-template'
repo_url: 'https://github.com/inetum-peru/base-template'
copyright: 'Copyright © 2021 <a href="http://www.gfiworld.com.pe">inetum-peru</a>'

google_analytics:
  - ''
  - 'auto'
